[package]
name = "validate_detection_rule_json"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonschema = "0.33.0"
serde = "1.0.219"
serde_json = "1.0.143"

[dev-dependencies]
assert_fs = "1.1.3"
