[tasks.release-check]
description = "Run fmt check, build, test, and clippy"
script = [
    "cargo fmt --all -- --check",
    "cargo build",
    "cargo test",
    "cargo clippy --all-targets -- -D warnings"
]
